### ISSUE TITLE
Tagging Properties and Filtering

### ISSUE THREAD

**Issue by incaseoftrouble** [sosy-lab/benchexec#998]
Based on discussion:

I propose to allow to attach arbitrary tags to properties in task-definitions:
```yml
properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true
    tags:
      - fast
      - ci
  - property_file: ../properties/valid-memsafety.prp
    expected_verdict: false
    subproperty: valid-memtrack
    tags:
      - false_properties
```
(`tags` can be replaced with a similar name, e.g., `labels`, but I think `tag` is appropriate)

The type is `Optional[set[str]]` 

The tags can be "selected" by `--require-tags [list of strings]` (require all given tags to be present) `--exclude-tags [list of strings]` (require no given tag to be present) or in similar format inside `<tasks>`.

---

A more powerful version would be an expression structure like
```xml
<filter> <!-- by default an and constraint -->
  <or><tag>a</tag><tag>b</tag></or>
  <not><tag>x</tag></not>
</filter>
```
so just defining a propositional formula with atomic propositions that can be derived from model and properties. This proposal "only" adds `tag` filtering but it shouldn't be hard to add more (FWIW a tool info could provide such information...)

The second part definitely is more of a "far fetched" idea and rather advanced. But would allow for a lot of control for advanced users.
